version: "3.9"
services:
    web:
        image: nginx:1.26-alpine
        ports:
            - "8080:80"
        volumes:
            - ./220240522_kobu.pdf:/usr/share/nginx/html/220240522_kobu.pdf
            - ./index.html:/usr/share/nginx/html/index.html
